### ISSUE TITLE
新版使用报错

### ISSUE THREAD

**Issue by Kenhuey** [ed-3/AdvancedAnnouncement#2]
执行命令，请求 example 公告
```
/aa broadcast chat_announce_type_example
```

```
[02:15:02] [Craft Scheduler Thread - 36/WARN]: [AdvancedAnnouncement] Plugin AdvancedAnnouncement v1.2.6-release generated an exception while executing task 63
java.lang.NoClassDefFoundError: Could not initialize class top.ed333.mcplugin.advancedann.bukkit.utils.ProtocolUtils
        at top.ed333.mcplugin.advancedann.bukkit.announcement.Announcement$1.run(Announcement.java:90) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-090a6ffb]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-090a6ffb]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_202]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
>
```

**Comment by ed-3** [comment]
bukkit插件需要安装 protocollib 和 placeholderapi
这两个插件为硬依赖必须安装
